name: yaml_prop
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - matplotlib
  - numpy
  - scipy
  - pyyaml
  - numexpr
  - pip
  - pip:
    - pint
    - mip
    - pyyaml-include>=2
